apps/accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
  path('perfil/', views.Perfil.as_view(), name='perfil'),
  path('perfil-atualiza/<int:pk>/', views.Perfil_atualiza.as_view(), name='perfil-atualiza'),
  path('perfil-excluir/<int:pk>/', views.Perfil_excluir.as_view(), name='perfil-excluir'),
  path('favoritos/', views.favoritos, name='favoritos'),
  path('sobre-produto-favorito/<int:pk>', views.sobre_produto_favorito, name='sp-favorito'),
]

iraci_modas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.core.views import view_404
handler404 = view_404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('apps.accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from email.headerregistry import Address
from django.db import models
from django.contrib.auth.models import AbstractUser

from .validate import validate_CPF


GENRE = (
  ('Masculino', 'Masculino'),
  ('Feminino', 'Feminino'),
  ('Outro', 'Outro'),
)


class User(AbstractUser):
  genre = models.CharField(max_length=9, choices=GENRE, verbose_name='Gênero')
  birth_date = models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')
  cpf = models.CharField(max_length=14, verbose_name='CPF', validators=[validate_CPF])
  address = models.CharField(max_length=120, verbose_name='Endereço')
  telephone = models.CharField(max_length=20, verbose_name='Telefone')
  zip_code = models.CharField(max_length=20, verbose_name='CEP')
  district = models.CharField(max_length=120, verbose_name='Bairro')

  def __str__(self):
    return self.username

apps/accounts/forms.py
from allauth.account.forms import SignupForm
from django import forms as as_forms
from django.contrib.auth import forms

from .models import User, GENRE
from .validate import validate_CPF


class UserChangeForm(forms.UserChangeForm):
  class Meta(forms.UserChangeForm.Meta):
    model = User


class UserCreationForm(forms.UserCreationForm):
  class Meta(forms.UserCreationForm.Meta):
    model = User


class MyCustomSignupForm(SignupForm):
  first_name = as_forms.CharField(label='Primeiro Nome')
  last_name = as_forms.CharField(label='Sobrenome')
  genre = as_forms.CharField(label='Gênero')
  birth_date = as_forms.CharField(label='Data de Nascimento')
  cpf = as_forms.CharField(label='CPF', validators=[validate_CPF])
  address = as_forms.CharField(label="Endereço")
  telephone = as_forms.CharField(label='Telefone')
  zip_code = as_forms.CharField(label="CEP")
  district = as_forms.CharField(label="Bairro")

  def __init__(self, *args, **kwargs):
    super(MyCustomSignupForm, self).__init__(*args, **kwargs)
    self.fields['first_name'].widget = as_forms.TextInput(attrs={'placeholder': 'Primeiro Nome'})
    self.fields['last_name'].widget = as_forms.TextInput(attrs={'placeholder': 'Sobrenome'})
    self.fields['genre'].widget = as_forms.RadioSelect(attrs={'placeholder': 'Gênero'}, choices=GENRE)
    self.fields['birth_date'].widget = as_forms.DateInput(format='%d/%m/%Y', attrs={'placeholder': 'Data de Nascimento', 'type': 'date'})
    self.fields['cpf'].widget = as_forms.TextInput(attrs={'placeholder': 'CPF'})
    self.fields['address'].widget = as_forms.TextInput(attrs={'placeholder': 'Endereço'})
    self.fields['telephone'].widget = as_forms.TextInput(attrs={'placeholder': 'Telefone'})
    self.fields['zip_code'].widget = as_forms.TextInput(attrs={'placeholder': 'CEP'})
    self.fields['district'].widget = as_forms.TextInput(attrs={'placeholder': 'Bairro'})

  def save(self, request):
    user = super(MyCustomSignupForm, self).save(request)
    user.first_name = self.cleaned_data['first_name']
    user.username = user.username.capitalize()
    user.last_name = self.cleaned_data['last_name']
    user.genre = self.cleaned_data['genre']
    user.birth_date = self.cleaned_data['birth_date']
    user.cpf = self.cleaned_data['cpf']
    user.address = self.cleaned_data['address']
    user.telephone = self.cleaned_data['telephone']
    user.zip_code = self.cleaned_data['zip_code']
    user.district = self.cleaned_data['district']
    user.save()
    return user

apps/accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.db.models import fields

from apps.product.models import Product
from .models import User


class Perfil(LoginRequiredMixin, ListView):
  login_url = reverse_lazy('account_login')
  model = User
  template_name = 'accounts/perfil.html'

  def get_queryset(self):
    self.object_list = User.objects.filter(first_name=self.request.user)
    return self.object_list


class Perfil_atualiza(LoginRequiredMixin, UpdateView):
  login_url = reverse_lazy('account_login')
  model = User
  fields = ['address', 'telephone', 'zip_code', 'district']
  template_name = 'accounts/perfil_atualiza.html'
  success_url = reverse_lazy('perfil')

  def get_object(self, queryset=None):
    self.object = get_object_or_404(User, pk=self.kwargs['pk'], first_name=self.request.user)
    return self.object


class Perfil_excluir(LoginRequiredMixin, DeleteView):
  login_url = reverse_lazy('account_login')
  model = User
  template_name = 'accounts/perfil_excluir.html'
  success_url = reverse_lazy('perfil')

  def get_object(self, queryset=None):
    self.object = get_object_or_404(User, pk=self.kwargs['pk'], first_name=self.request.user)
    return self.object


@login_required
def favoritos(request):
  user = request.user
  product = user.favorite.all()
  return render(request, 'accounts/favoritos.html', {'product':product})

@login_required
def sobre_produto_favorito(request, pk):
  product = get_object_or_404(Product, pk=pk)
  
  if request.method == 'POST':
    if product.favorite.filter(id=request.user.id).exists():
      product.favorite.remove(request.user)

      return redirect('favoritos')
      
  return render(request, 'accounts/sobre_produto_favorito.html', {'product':product})

apps/accounts/templates/accounts/favoritos.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Favoritos.">

  <title>Iraci Modas | Favoritos</title>

  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
  <link rel="preload" href="{% static 'css/style.min.css' %}" as="style">
  <link rel="stylesheet" href="{% static 'css/style.min.css' %}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&family=Roboto:wght@400;500&display=swap" rel="stylesheet">
</head>

<body id="favoritos">
  <header class="header-bg">
    <div class="header container">
      <a href="{% url 'home' %}">
        <img src="{% static 'img/logo.png' %}" alt="Logo: Iraci Modas">
      </a>

      <nav aria-label="primary">
        <ul class="header-menu font-1-m cor-0">
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'galeria-todos' %}">Galeria</a></li>
          <li><a href="{% url 'contato-sobre' %}">Contato</a></li>
          <li><a href="{% url 'favoritos' %}">Favoritos</a></li>
        </ul>
      </nav>
      <nav aria-label="secondary">
        <ul class="header-menu font-1-m cor-0">
          <li>
            {% if user.is_authenticated %}
            <a href="{% url 'perfil' %}">Perfil</a>
            {% else %}
            <a href="{% url 'account_login' %}">Login</a>
            {% endif %}
          </li>
        </ul>
      </nav>
    </div>
  </header>

  <main>
    <div class="titulo-bg">
      <div class="titulo container">
        <p class="font-2-l-b cor-11">Olá, <span class="cor-i-3">{{ user.username }}</span>.</p>
        <h1 class="font-1-xxl cor-10">
          Favoritos</span>
        </h1>
      </div>
    </div>
  </main>

  <article class="galeria-lista">
    <h2 class="container font-1-xxl">
      Seus favoritos
    </h2>

    <ul>
      {% for product in product %}
      <li>
        <a href="{% url 'sp-favorito' product.pk %}">
          <img src="{{ product.image.url }}" alt="home1" width="400" height="1040">
          <h3 class="font-1-xl">{{ product.name }}</h3>
          <span class="font-2-m cor-8">{{ product.category }}</span>
          <span class="font-2-m cor-8">{{ product.price }}</span>
        </a>
      </li>
      {% endfor %}
    </ul>
  </article>

  <footer class="footer-bg">
    <div class="footer container">
      <img src="{% static 'img/logo.png' %}" width="136" height="32" alt="Logo: Iraci Modas">
      <div class="footer-contato">
        <h3 class="font-2-l-b cor-0">Contato</h3>
        <ul class="font-2-m cor-5">
          <li><a href="tel:+5589994411460">+55 89 99441-1460</a></li>
          <li>
            <a href="mailto:iraciholanda4@gmail.com">iraciholanda4@gmail.com</a>
          </li>
          <li>Povoado Lagoa Grande - Zona Rural</li>
          <li>Picos - PI</li>
        </ul>
        <div class="footer-redes">
          <a href="https://www.instagram.com/iraci_modass/" target="_blank">
            <img src="{% static 'img/redes/instagram.svg' %}" width="32" height="32" alt="Instagram">
          </a>
          <a href="https://www.facebook.com/iraci.holanda.9" target="_blank">
            <img src="{% static 'img/redes/facebook.svg' %}" width="32" height="32" alt="Facebook">
          </a>
          <!-- <a href="./">
            <img src="../img/redes/youtube.svg" width="32" height="32" alt="Youtube">
          </a> -->
        </div>
      </div>
      <div class="footer-informacoes">
        <h3 class="font-2-l-b cor-0">Informações</h3>
        <nav>
          <ul class="font-1-m cor-5">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'galeria-todos' %}">Galeria</a></li>
            <li><a href="{% url 'contato-sobre' %}">Contato</a></li>
            <li><a href="{% url 'favoritos' %}">Favoritos</a></li>
            <li>
              {% if user.is_authenticated %}
              <a href="{% url 'perfil' %}">Perfil</a>
              {% else %}
              <a href="{% url 'account_login' %}">Login</a>
              {% endif %}
            </li>
          </ul>
        </nav>
      </div>
      <p class="footer-copy font-2-m cor-6">
        Iraci Modas ©
        <script>
          document.write(new Date().getFullYear())
        </script>
        | Alguns direitos reservados.
      </p>
    </div>
  </footer>
  <script src="{% static 'js/plugins/simple-anime.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

apps/accounts/templates/accounts/perfil.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Perfil.">
  <title>Iraci Modas | Perfil</title>

  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
  <link rel="preload" href="{% static 'css/style.min.css' %}" as="style">
  <link rel="stylesheet" href="{% static 'css/style.min.css' %}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&family=Roboto:wght@400;500&display=swap" rel="stylesheet">
</head>

<body id="perfil">
  <header class="header-bg">
    <div class="header container">
      <a href="{% url 'home' %}">
        <img src="{% static 'img/logo.png' %}" alt="Logo: Iraci Modas">
      </a>

      <nav aria-label="primary">
        <ul class="header-menu font-1-m cor-0">
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'galeria-todos' %}">Galeria</a></li>
          <li><a href="{% url 'contato-sobre' %}">Contato</a></li>
          <li><a href="{% url 'favoritos' %}">Favoritos</a></li>
        </ul>
      </nav>
      <nav aria-label="secondary">
        <ul class="header-menu font-1-m cor-0">
          <li>
            {% if user.is_authenticated %}
            <a href="{% url 'perfil' %}">Perfil</a>
            {% else %}
            <a href="{% url 'account_login' %}">Login</a>
            {% endif %}
          </li>
        </ul>
      </nav>
    </div>
  </header>

  <main>
    <div class="titulo-bg">
      <div class="titulo container">
        <p class="font-2-l-b cor-11"></p>
        <h1 class="font-1-xxl cor-10">
          Seus dados</span>
        </h1>
      </div>
    </div>

    <div class="usuario container">
      <section class="usuario-formulario fadeInRight" aria-label="Formulário" data-anime="400">
        <form class="form" action="{% url 'account_logout' %}" method="post">

          {% csrf_token %}
          {% for object in object_list %}

          <div class="col-2">
            <label for="id_nome">Nome Completo</label>
            <input type="text" id="id_nome" name="nome" value="{{ object.first_name }} {{ object.last_name }}" readonly>
          </div>
          <div class="col-2">
            <label for="id_genero">Gênero</label>
            <input type="text" id="id_genero" name="genero" value="{{ object.genre }}" readonly>
          </div>
          <div class="">
            <label for="id_data">Data de Nascimento</label>
            <input type="text" id="id_data" name="data_de_nascimento" value="{{ object.birth_date }}" readonly>
          </div>
          <div class="">
            <label for="id_cpf">CPF</label>
            <input type="text" id="id_cpf" name="CPF" value="{{ object.cpf }}" readonly>
          </div>
          <div class="">
            <label for="id_email">E-mail</label>
            <input type="email" id="id_email" name="email" value="{{ object.email }}" readonly>
          </div>
          <div class="">
            <label for="id_telefone">Telefone</label>
            <input type="tel" id="id_telefone" name="telefone" value="{{ object.telephone }}" readonly>
          </div>
          <div class="col-2">
            <label for="id_endereco">Endereço</label>
            <input type="text" id="id_endereco" name="endereco" value="{{ object.address }}" readonly>
          </div>
          <div class="">
            <label for="id_cep">CEP</label>
            <input type="text" id="id_cep" name="cep" value="{{ object.zip_code }}" readonly>
          </div>
          <div class="">
            <label for="id_bairro">Bairro</label>
            <input type="text" id="id_bairro" name="bairro" value="{{ object.district }}" readonly>
          </div>
          <p>Deseja atualizar seus dados? <a href="{% url 'perfil-atualiza' object.pk %}">Atualizar</a></p>
          <p>Deseja excluir seus dados? <a href="{% url 'perfil-excluir' object.pk %}">Excluir</a></p>
          {% empty %}
          <tr>
            <td colspan="3">Sem Informações</td>
          </tr>
          {% endfor %}
          <button class="botao col-2">Sair</button>
          <!--<p class="">Deseja sair? <a class="" href="{% url 'account_logout' %}">Sair</a></p>-->
          <p>Ao continuar com o acesso, você concorda com a nossa <span>política de privacidade.</span></p>
        </form>
      </section>
    </div>
  </main>

  <footer class="footer-bg">
    <div class="footer container">
      <img src="{% static 'img/logo.png' %}" width="136" height="32" alt="Logo: Iraci Modas">
      <div class="footer-contato">
        <h3 class="font-2-l-b cor-0">Contato</h3>
        <ul class="font-2-m cor-5">
          <li><a href="tel:+5589994411460">+55 89 99441-1460</a></li>
          <li>
            <a href="mailto:iraciholanda4@gmail.com">iraciholanda4@gmail.com</a>
          </li>
          <li>Povoado Lagoa Grande - Zona Rural</li>
          <li>Picos - PI</li>
        </ul>
        <div class="footer-redes">
          <a href="https://www.instagram.com/iraci_modass/" target="_blank">
            <img src="{% static 'img/redes/instagram.svg' %}" width="32" height="32" alt="Instagram">
          </a>
          <a href="https://www.facebook.com/iraci.holanda.9" target="_blank">
            <img src="{% static 'img/redes/facebook.svg' %}" width="32" height="32" alt="Facebook">
          </a>
        </div>
      </div>
      <div class="footer-informacoes">
        <h3 class="font-2-l-b cor-0">Informações</h3>
        <nav>
          <ul class="font-1-m cor-5">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'galeria-todos' %}">Galeria</a></li>
            <li><a href="{% url 'contato-sobre' %}">Contato</a></li>
            <li><a href="{% url 'favoritos' %}">Favoritos</a></li>
            <li>
              {% if user.is_authenticated %}
              <a href="{% url 'perfil' %}">Perfil</a>
              {% else %}
              <a href="{% url 'account_login' %}">Login</a>
              {% endif %}
            </li>
          </ul>
        </nav>
      </div>
      <p class="footer-copy font-2-m cor-6">
        Iraci Modas ©
        <script>
          document.write(new Date().getFullYear())
        </script>
        | Alguns direitos reservados.
      </p>
    </div>
  </footer>
  <script src="{% static 'js/plugins/simple-anime.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

apps/accounts/templates/accounts/perfil_atualiza.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Atualizar dados.">
  <title>Iraci Modas | Atualiza</title>

  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
  <link rel="preload" href="{% static 'css/style.min.css' %}" as="style">
  <link rel="stylesheet" href="{% static 'css/style.min.css' %}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&family=Roboto:wght@400;500&display=swap" rel="stylesheet">
</head>

<body id="perfil-dados">
  <header class="header-bg">
    <div class="header container">
      <a href="{% url 'home' %}">
        <img src="{% static 'img/logo.png' %}" alt="Logo: Iraci Modas">
      </a>

      <nav aria-label="primary">
        <ul class="header-menu font-1-m cor-0">
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'galeria-todos' %}">Galeria</a></li>
          <li><a href="{% url 'contato-sobre' %}">Contato</a></li>
          <li><a href="{% url 'favoritos' %}">Favoritos</a></li>
        </ul>
      </nav>
      <nav aria-label="secondary">
        <ul class="header-menu font-1-m cor-0">
          <li>
            {% if user.is_authenticated %}
            <a href="{% url 'perfil' %}">Perfil</a>
            {% else %}
            <a href="{% url 'account_login' %}">Login</a>
            {% endif %}
          </li>
        </ul>
      </nav>
    </div>
  </header>

  <main>
    <div class="titulo-bg">
      <div class="titulo container">
        <p class="font-2-l-b cor-11">Caso você queira atualizar seus dados</p>
        <h1 class="font-1-xxl cor-10">
          Atualizar seus dados</span>
        </h1>
      </div>
    </div>

    <div class="usuario container">
      <section class="usuario-formulario fadeInRight" aria-label="Formulário" data-anime="400">
        <form class="form" action="" method="post">

          {% csrf_token %}
          {{ form|crispy }}

          <button class="botao col-2">atualizar</button>
          <p class="">Deseja sair? <a class="" href="{% url 'account_logout' %}">Sair</a></p>
          <p>Caso queira atualizar algum dado específico que não <br> esteja disponível entre com <a href="{% url 'contato-sobre' %}">contato</a>.</p>
          <p>Ao continuar com o acesso, você concorda com a nossa <span>política de privacidade.</span></p>

        </form>
      </section>
    </div>
  </main>

  <footer class="footer-bg">
    <div class="footer container">
      <img src="{% static 'img/logo.png' %}" width="136" height="32" alt="Logo: Iraci Modas">
      <div class="footer-contato">
        <h3 class="font-2-l-b cor-0">Contato</h3>
        <ul class="font-2-m cor-5">
          <li><a href="tel:+5589994411460">+55 89 99441-1460</a></li>
          <li>
            <a href="mailto:iraciholanda4@gmail.com">iraciholanda4@gmail.com</a>
          </li>
          <li>Povoado Lagoa Grande - Zona Rural</li>
          <li>Picos - PI</li>
        </ul>
        <div class="footer-redes">
          <a href="https://www.instagram.com/iraci_modass/" target="_blank">
            <img src="{% static 'img/redes/instagram.svg' %}" width="32" height="32" alt="Instagram">
          </a>
          <a href="https://www.facebook.com/iraci.holanda.9" target="_blank">
            <img src="{% static 'img/redes/facebook.svg' %}" width="32" height="32" alt="Facebook">
          </a>
        </div>
      </div>
      <div class="footer-informacoes">
        <h3 class="font-2-l-b cor-0">Informações</h3>
        <nav>
          <ul class="font-1-m cor-5">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'galeria-todos' %}">Galeria</a></li>
            <li><a href="{% url 'contato-sobre' %}">Contato</a></li>
            <li><a href="{% url 'favoritos' %}">Favoritos</a></li>
            <li>
              {% if user.is_authenticated %}
              <a href="{% url 'perfil' %}">Perfil</a>
              {% else %}
              <a href="{% url 'account_login' %}">Login</a>
              {% endif %}
            </li>
          </ul>
        </nav>
      </div>
      <p class="footer-copy font-2-m cor-6">
        Iraci Modas ©
        <script>
          document.write(new Date().getFullYear())
        </script>
        | Alguns direitos reservados.
      </p>
    </div>
  </footer>
  <script src="{% static 'js/plugins/simple-anime.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

apps/accounts/templates/accounts/perfil_excluir.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Perfil.">
  <title>Iraci Modas | Perfil</title>

  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
  <link rel="preload" href="{% static 'css/style.min.css' %}" as="style">
  <link rel="stylesheet" href="{% static 'css/style.min.css' %}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&family=Roboto:wght@400;500&display=swap" rel="stylesheet">
</head>

<body id="perfil">
  <header class="header-bg">
    <div class="header container">
      <a href="{% url 'home' %}">
        <img src="{% static 'img/logo.png' %}" alt="Logo: Iraci Modas">
      </a>

      <nav aria-label="primary">
        <ul class="header-menu font-1-m cor-0">
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'galeria-todos' %}">Galeria</a></li>
          <li><a href="{% url 'contato-sobre' %}">Contato</a></li>
          <li><a href="{% url 'favoritos' %}">Favoritos</a></li>
        </ul>
      </nav>
      <nav aria-label="secondary">
        <ul class="header-menu font-1-m cor-0">
          <li>
            {% if user.is_authenticated %}
            <a href="{% url 'perfil' %}">Perfil</a>
            {% else %}
            <a href="{% url 'account_login' %}">Login</a>
            {% endif %}
          </li>
        </ul>
      </nav>
    </div>
  </header>

  <main>
    <div class="titulo-bg">
      <div class="titulo container">
        <p class="font-2-l-b cor-11"></p>
        <h1 class="font-1-xxl cor-10">
          Excluir Seus dados</span>
        </h1>
      </div>
    </div>

    <div class="usuario container">
      <section class="usuario-formulario fadeInRight" aria-label="Formulário" data-anime="400">
        <form class="form" action="" method="post">

          <p class="obrigatorio">
            Tem certeza que deseja excluir sua conta?<br>
            Essa ação não tem volta.
          </p>

          {% csrf_token %}
          {{ form.as_p }}

          <button class="botao col-2">Excluir sua conta</button>
          <p class="">Deseja sair? <a class="" href="{% url 'account_logout' %}">Sair</a></p>
          <p>Ao continuar com o acesso, você concorda com a nossa <span>política de privacidade.</span></p>
        </form>
      </section>
    </div>
  </main>

  <footer class="footer-bg">
    <div class="footer container">
      <img src="{% static 'img/logo.png' %}" width="136" height="32" alt="Logo: Iraci Modas">
      <div class="footer-contato">
        <h3 class="font-2-l-b cor-0">Contato</h3>
        <ul class="font-2-m cor-5">
          <li><a href="tel:+5589994411460">+55 89 99441-1460</a></li>
          <li>
            <a href="mailto:iraciholanda4@gmail.com">iraciholanda4@gmail.com</a>
          </li>
          <li>Povoado Lagoa Grande - Zona Rural</li>
          <li>Picos - PI</li>
        </ul>
        <div class="footer-redes">
          <a href="https://www.instagram.com/iraci_modass/" target="_blank">
            <img src="{% static 'img/redes/instagram.svg' %}" width="32" height="32" alt="Instagram">
          </a>
          <a href="https://www.facebook.com/iraci.holanda.9" target="_blank">
            <img src="{% static 'img/redes/facebook.svg' %}" width="32" height="32" alt="Facebook">
          </a>
        </div>
      </div>
      <div class="footer-informacoes">
        <h3 class="font-2-l-b cor-0">Informações</h3>
        <nav>
          <ul class="font-1-m cor-5">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'galeria-todos' %}">Galeria</a></li>
            <li><a href="{% url 'contato-sobre' %}">Contato</a></li>
            <li><a href="{% url 'favoritos' %}">Favoritos</a></li>
            <li>
              {% if user.is_authenticated %}
              <a href="{% url 'perfil' %}">Perfil</a>
              {% else %}
              <a href="{% url 'account_login' %}">Login</a>
              {% endif %}
            </li>
          </ul>
        </nav>
      </div>
      <p class="footer-copy font-2-m cor-6">
        Iraci Modas ©
        <script>
          document.write(new Date().getFullYear())
        </script>
        | Alguns direitos reservados.
      </p>
    </div>
  </footer>
  <script src="{% static 'js/plugins/simple-anime.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
</body>

</html>